version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: pdf-chat-agent
    ports:
      - "8000:8000"
    volumes:
        - ./agents:/app
    env_file:
        - .env
    depends_on:
      - chromadb    

  chromadb:
    image: chromadb_image 
    container_name: chromadb_service
    ports:
      - "8001:8001"
    volumes:
      - chroma_data:/chroma_data

volumes:
  chroma_data:
